package org.bmsource.ws.client;

import javax.xml.ws.WebFault;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "CardValidationFault", targetNamespace = "http://ws.bmsource.org/")
public class CardValidationException_Exception
        extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private final CardValidationException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public CardValidationException_Exception(String message, CardValidationException faultInfo)
    {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public CardValidationException_Exception(String message, CardValidationException faultInfo, Throwable cause)
    {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.bmsource.ws.CardValidationException
     */
    public CardValidationException getFaultInfo()
    {
        return faultInfo;
    }

}
