package org.bmsource.ws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Validator", targetNamespace = "http://ws.bmsource.org/")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface Validator
{

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     * @throws CardValidationException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "validate", targetNamespace = "http://ws.bmsource.org/", className = "org.bmsource.ws.Validate")
    @ResponseWrapper(localName = "validateResponse", targetNamespace = "http://ws.bmsource.org/", className = "org.bmsource.ws.ValidateResponse")
    @Action(input = "http://ws.bmsource.org/Validator/validateRequest", output = "http://ws.bmsource.org/Validator/validateResponse", fault = {
            @FaultAction(className = CardValidationException_Exception.class, value = "http://ws.bmsource.org/Validator/validate/Fault/CardValidationException")
    })
    public boolean validate(
        @WebParam(name = "arg0", targetNamespace = "") CreditCard arg0)
        throws CardValidationException_Exception;

}
